service: test-service

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.default
    events:
      - http:
          path: /
          method: get

  imageResize:
    handler: handler.contact
    events:
      - http:
          path: /contact
          method: get
